name: Release

on:
  push:
    tags:
      - '*'
    branches:
      # temporarily for testing:
      - move-to-github-actions

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask openpyxl pandas statsmodels xlrd
    - name: Build and publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pip install setuptools wheel twine
        python setup.py sdist bdist_wheel
        # twine upload dist/*
    - name: Built documentation and publish to gh-pages
      run: |
        pip install sphinx numpydoc
        cd docs
        make html
        git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/makr3la/regression.git --branch gh-pages --single-branch gh-pages
        cp -r docs/build/html/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        git push origin gh-pages
